name=blendixserial
version=2.1.0
author=usman
maintainer=Usman <help@electronicstree.com>
sentence=Compact bidirectional serial protocol for Blender ↔ Arduino 3D object control
paragraph=Delta-compressed protocol to send/receive location, rotation, scale (floats) of multiple 3D objects and short text messages between Blender (via blendixserial add-on) and Arduino/ESP32/etc. 
category=Communication
url=https://github.com/electronicstree/BlendixSerial-Arduino
architectures=*
includes=blendixserial.h